---
- name: I3 - Set required packages
  ansible.builtin.set_fact:
    i3_packages:
      - acpi
      - arandr
      - brightnessctl
      # - cpmpoton #
      # - dex-autostart
      - dmenu
      - dunst
      - feh
      - flameshot
      # - fonts-font-awesome #
      # - fonts-noto #
      # - fonts-liberation #
      - i3
      - i3blocks
      - i3lock
      - i3status
      - jq
      # - lightdm ##
      # - lightdm-gtk-greeter ##
      # - lightdm-gtk-greeter-settings ##

      # - lxappearance
      - network-manager
      # - network-manager-gnome #
      # - pulseaudio #
      # - pavucontrol #
      # - policykit-1-gnome #
      - rofi
      - scrot
      # - suckless-tools
      - thunar
      # - thunar-archive-plugin #
      # - thunar-media-tags-plugin #
      # - thunar-volman #
      - unzip
      - x11-xserver-utils
      - xfce4-terminal
      # - xbacklight #
      # - xorg ##
      # - xinit ##
      - xss-lock
      - zip

- name: I3 - Install packages
  ansible.builtin.package:
    name: "{{ i3_packages }}"
    state: present
  when: ansible_os_family == "Debian"
