---
- name: I3 - Set required packages
  ansible.builtin.set_fact:
    i3_packages:
      - acpi
      - arandr
      - brightnessctl
      - dex
      - dmenu
      - dunst
      - feh
      - flameshot
      - gvfs
      - i3
      - i3blocks
      - i3lock
      - i3status
      - i3-wm
      - jq
      - lightdm
      - network-manager-applet
      - pulseaudio
      - pavucontrol
      - rofi
      - scrot
      - sysstat
      - thunar
      - thunar-archive-plugin
      - thunar-volman
      - unzip
      - x11-xserver-utils
      - xarchiver
      - xfce4-terminal
      - xorg
      - xinit
      - xss-lock
      - zip

- name: I3 - Install packages
  ansible.builtin.package:
    name: "{{ i3_packages }}"
    state: present
  when: ansible_os_family == "Debian"
