---
sysinit_distro_packages:
  - postgresql

sysinit_tools: 
  - aws-ssm
  - docker 
  - opass
  - slack
  - warp

sysinit_tool_packages: 
  mkcert:
    - nss
  docker:
    - docker
    - docker-compose
  aws-ssm:
    - rpmextract  # Provides rpm2cpio for extracting RPM files
