---
sysinit_distro_packages:
  - postgresql-client

sysinit_tools:
  - aws-ssm
  - docker

# Tool-specific package dependencies
sysinit_tool_packages:
  mkcert:
    - libnss3-tools
  chrome:
    - ca-certificates
    - curl
    - gnupg
  docker:
    - ca-certificates
    - curl
    - gnupg
